# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['src/sports_proctor/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/sports_proctor/assets', 'assets'),
        ('src/sports_proctor/models', 'models'),
    ],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtMultimedia',
        'PyQt6.QtMultimediaWidgets',
        'cv2',
        'mediapipe',
        'numpy',
        'pandas',
        'pyttsx3',
        'pyaudio',
        'pygame',
        'ultralytics',
        'fastapi',
        'uvicorn',
        'motor',
        'matplotlib',
        'PIL',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Sports_Proctor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='build/icon.ico',
)
